---
name: Build documentation
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'docs/design/*.md'
      - 'docs/design/*.order'
      - 'docs/design/.attachments/**'
  push:
    paths:
      - 'docs/design/*.md'
      - 'docs/design/*.order'
      - 'docs/design/.attachments/**'

jobs:
  pdf:
    name: Build PDF
    uses: innofactororg/ghw-markdown-convert/.github/workflows/build-documentation.yml@main
    secrets: inherit
    with:
      OrderFile: design/pdfDocument.order
      OutFile: azGovernance-document.pdf