---
name: Process Main example
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '*.tf'



jobs:

  process-main-definition:
    name: Process Main Definition
    uses: ./.github/workflows/_build_definition.yml
    secrets: inherit